apiVersion: v1
kind: Service
metadata:
  name: webapi-lb
  labels:
    app: webapi
spec:
  selector:
    app: webapi
  ports:
    - name: http
      port: 9900
      targetPort: 9900
  type: LoadBalancer