apiVersion: apps/v1 
kind: Deployment
metadata:
  name: webapi
  labels:
    app: webapi
spec:
  selector:
    matchLabels:
      app: webapi
      tier: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: webapi
        tier: backend
    spec:
      containers:
      - name: webapi
        image: webapi/webapi:staging
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 9900
        imagePullPolicy: Never
        env:
          - name: DomainConnectionString
            value: "Data Source=host.docker.internal;Initial Catalog=DEV;Trusted_Connection=false;Persist Security Info=True;User ID=dev;Password=dev@12345"
          - name: RedisConnectionString
            value: "10.1.0.144"

